"""Final deterministic QA for visible infographic content."""

from __future__ import annotations

import re

from gqmrmed.ai.infographic_design import InfographicDesignSpec

_URL_RE = re.compile(r"https?://|www\\.", re.IGNORECASE)
_FORBIDDEN_VISIBLE = (
    "generated by ai",
    "ai generated",
    "source:",
    "sources:",
    "prompt:",
    "watermark",
)


class InfographicQAError(ValueError):
    """Raised when a final design violates deterministic output rules."""


def validate_design_spec(spec: InfographicDesignSpec) -> None:
    """Reject visible content that leaks metadata or breaks the composition contract."""
    if not spec.pages:
        raise InfographicQAError("infographic_has_no_pages")
    if spec.branding.telegram_handle != "QMR7S":
        raise InfographicQAError("unexpected_branding_handle")
    for page in spec.pages:
        if not page.blocks:
            raise InfographicQAError("infographic_page_has_no_content")
        for block in page.blocks:
            text = " ".join(block.text.split())
            if not text:
                raise InfographicQAError("infographic_empty_text_block")
            if _URL_RE.search(text):
                raise InfographicQAError("visible_source_url_forbidden")
            lowered = text.lower()
            if any(marker in lowered for marker in _FORBIDDEN_VISIBLE):
                raise InfographicQAError("visible_metadata_text_forbidden")
            if len(text) > 2_000:
                raise InfographicQAError("visible_text_block_too_long")


__all__ = ["InfographicQAError", "validate_design_spec"]
